#!/usr/bin/env bash
# QUICK REFERENCE CARD - Copy & Paste Commands

echo "🚀 CHAINPULSE - SUPPLY CHAIN INTELLIGENCE SYSTEM"
echo "==============================================="
echo ""
echo "📋 QUICK COMMANDS:"
echo ""
echo "Install dependencies:"
echo "  pip install -r requirements.txt"
echo ""
echo "Run all features at once:"
echo "  python launch_all.py"
echo ""
echo "OR run individual features:"
echo ""
echo "Command Center (Executive Dashboard):"
echo "  streamlit run command_center.py"
echo "  👉 http://localhost:8501"
echo ""
echo "Copilot Chat (AI Questions):"
echo "  streamlit run copilot_chat.py"
echo "  👉 http://localhost:8502"
echo ""
echo "Digital Twin (What-If Scenarios):"
echo "  streamlit run digital_twin.py"
echo "  👉 http://localhost:8503"
echo ""
echo "News Intelligence (Real-Time Alerts):"
echo "  streamlit run news_intelligence.py"
echo "  👉 http://localhost:8504"
echo ""
echo "Mobile Dashboard:"
echo "  python dashboard_api.py"
echo "  👉 http://localhost:5000"
echo ""
echo "==============================================="
echo "📚 DOCUMENTATION:"
echo "  - GETTING_STARTED.md (START HERE)"
echo "  - IMPLEMENTATION_GUIDE.md (DETAILED)"
echo "  - README.md (ARCHITECTURE)"
echo ""
echo "==============================================="
